### ISSUE TITLE
on my laptop not every click is accepted and the tool doesn't switch pages 

### ISSUE THREAD

**Issue by Tasek** [Unponderable/NGU-Rebirth-Script#11]
As the title already says, not every click is accepted (only on laptop, pc works). i think it's the tooltip option, it hides many options like Fight boss etc. On the PC they are not hidden (same screen resolution). The tooltip screen is bigger on my laptop especially when long words are displayed.

**Comment by SilverRatchet** [comment]
i had that problem too some time ago... but it solved itself just by changing the resolution of the window. in my case the script only works correctly if i run it with the game with the default resolution of 960*600
