### ISSUE TITLE
Augmentations not working

### ISSUE THREAD

**Issue by PhoenixFire54** [Unponderable/NGU-Rebirth-Script#13]
When the script tries to put energy into the augmentation I have selected it will go to the augmentation page as if it is about to deposit the energy, but it won't actually put the energy into anything. Instead, it will just skip the step and go to the next thing as if it did put the energy into the augmentation.

**Comment by Unponderable** [comment]
When this issue occurred, was the augment already maxed out (i.e., blue
barred, earning 50 levels per second)? It is designed not to add excess
energy if that is the case.

**Comment by PhoenixFire54** [comment]
Sorry for a late response, but no, the augment was not maxed out, this was happening at the very beginning of the rebirth before any energy was put into the augment.

**Comment by PhoenixFire54** [comment]
Another thing that isn't really noteworthy enough for its own thread is that the blood magic ritual in the script is called "filthy paper cuts" when in the game it is called "fifty paper cuts."

**Comment by PhoenixFire54** [comment]
I'm not quite sure what happened, but it seems like the augmentation problem has been fixed and now the script is correctly putting energy into my augments.

**Comment by PhoenixFire54** [comment]
I'm not quite sure what happened, but it seems like the augmentation problem has been fixed and now the script is correctly putting energy into my augments.
