### ISSUE TITLE
Nothing happens when NGU's are enabled

### ISSUE THREAD

**Issue by rakafo** [Unponderable/NGU-Rebirth-Script#14]
No skills are being learned and there isn't a GUI option to choose. Is it broken or are there additional requirements implied?

**Comment by Unponderable** [comment]
Were you running a challenge? NGUs are intentionally disabled during challenge runs to save energy/magic.

**Comment by rakafo** [comment]
Plain 15 min rebirths. As per my workaround, modifying the if clause EnableNGUs in function RebirthScript_Short to 	

if EnableNGUs
		{
			NGUBloodAssign() (or a custom to only assign NGU)
			NGU_CapBoth()
		}

executes NGUs correctly, whereas if it's left with only with NGU_CapBoth() then it open NGU menu, but doesn't do anything.
