### ISSUE TITLE
Mouse cursor not moving to correct locations

### ISSUE THREAD

**Issue by sludgeporpoise** [Unponderable/NGU-Rebirth-Script#16]
Does this script still work?

I believe I have everything set up correctly. 1920x1080 resolution, text and image scaling set to 100%. The script starts and the mouse moves, but it is obviously not hitting the right buttons. Random things come up on the screen for a minute or so with no actual changes to the game happening. I shut it down after a minute or so. Any ideas?

**Comment by Arumba07** [comment]
The script broke when the most recent patch, 1.101, went live.  This added a new button to the interface, shifting positions for most of the other buttons.  I have a functioning version, though I make no promises and this is my own personally tweaked version.  You can download it here: [MasterScript.zip](https://github.com/Unponderable/NGU-Rebirth-Script/files/4174364/MasterScript.zip)
Replace MasterScript.ahk in your folder with this version and it should work again.

Note that I've made a few personal changes to the script for my own purposes.  The pause key is now "tilde", the interface doesn't obscure the game, and probably other changes I've forgotten about.

Also, in my experience the script only functions on 960x600 resolution.  I'm not even sure how you got NGU to run at 1920x1080 without using some third party program to scale it.

**Comment by sludgeporpoise** [comment]
Awesome, thank you! I'll give it a try later today.

When I said 1920x1080 I was referring to the overall screen resolution. My monitor's native resolution is higher than that, so the script couldn't start until I changed the resolution in Windows. I was probably running ngu at 960x600 as you mentioned.

**Comment by sludgeporpoise** [comment]
Works perfectly now :)

**Comment by Unponderable** [comment]
I went ahead and updated the main script repository with the new coordinates you found, Arumba. Glad it works for you now, sludgeporpoise. Sorry about the resolution issue - at one point I tried to figure out a solution that would scale resolutions better, but I wasn't good enough of a programmer, sadly.
