### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by NeonWizard** [Unponderable/NGU-Rebirth-Script#4]
Hey, this tool is pretty cool, but there's a few things that aren't working properly with the last few updates. If you could go in and touch them up that would be amazing.

**Comment by Unponderable** [comment]
Thanks. Would be helpful if you could provide me with examples of what isn't working. I'm already aware of  energy/magic selections needing to be fixed.

**Comment by NeonWizard** [comment]
Yeah the custom energy buttons were the only issue I've seen. Closed this issue because I misread the timestamps on the AHK file.
