### ISSUE TITLE
Only rebirth if not fighting

### ISSUE THREAD

**Issue by kolhed** [Unponderable/NGU-Rebirth-Script#5]
probably since 0.413, if we try to rebirth while fighting a boss I get a tooltip saying that I am not allowed to rebirth while fighting...
This results in not rebirthing but the script keeps going as if it did...

Right now I came back to 21min rebirthtime, even if it should have done a rebirth every 4min.

Idea for solution: detect if the "Are you sure you want to rebirth" box pops up instead of just clicking where it assumes the box should be.

**Comment by GeertJanP85** [comment]
I also seen this problem with my 30min runs that goes to 1 hours runs.

**Comment by Unponderable** [comment]
Thanks for the report. I have it click the stop button now after it clicks the fight button.
